### ISSUE TITLE
What are the differences between bpystubgen & fake-bpy-module?

### ISSUE THREAD

**Issue by hannesdelbeke** [nutti/fake-bpy-module#117]
What are the differences between this [bpystubgen ](https://github.com/mysticfall/bpystubgen) & [fake-bpy-module](https://github.com/nutti/fake-bpy-module) (this repo)?
They both appear to serve the same goal, so it seems smart to inform github users about the differences so they can make an informed decision which one to use.

linked issue: https://github.com/mysticfall/bpystubgen/issues/4

**Comment by nutti** [comment]
@hannesdelbeke 

bpystubgen is a derived project of fake-bpy-module (In the past, I collaborated with the author of bpystubgen).
There are some projects whose goal is same as fake-bpy-module, and bpystubgen is one of them.
In my opinion, bpystubgen targets for fast generation and UPBGE.
bpystubgen generate module based on the API documentation, so some modules like `addon_utils` are missing.

I think the advantage of fake-bpy-module is as follows.

* The number of users
  * This makes the module well tested and coverage.
  * You can see [the closed issue list](https://github.com/nutti/fake-bpy-module/issues?q=is%3Aissue+is%3Aclosed) that includes the corner case which makes the auto completion more accurate.
* Support undocumented APIs
  * Support almost all modules provided by the Blender like `addon_utils`.
* Long term support
  * This project has continued since 2017. (I'm not sure this is a advantage or not)

The advantage described in bpystubgen will also be introduced in this project in the future.
For example, I recently refactored the code to generate the module 5X~ faster.
