### ISSUE TITLE
Fields that should be Color, Quaternion etc are all rendered as Vector.

### ISSUE THREAD

**Issue by angavrilov** [nutti/fake-bpy-module#126]
It is necessary to find a way to distinguish fields of different mathutils vector variants, which are currently all represented as Vector.

It seems the difference is not reflected in official API documentation, but it is of course known to Blender itself through the `subtype` property of RNA metadata:

```
>>> bpy.types.ThemeView3D.bl_rna.properties['wire'].subtype  # Color
'COLOR_GAMMA' 

>>> bpy.types.Object.bl_rna.properties['color'].subtype  # bpy_prop_array
'COLOR'

>>> bpy.types.Object.bl_rna.properties['rotation_quaternion'].subtype  # Quaternion
'QUATERNION' 

>>> bpy.types.Object.bl_rna.properties['rotation_euler'].subtype  # Euler
'EULER'

>>> bpy.types.Object.bl_rna.properties['rotation_axis_angle'].subtype  # bpy_prop_array
'AXISANGLE'

>>> bpy.types.Object.bl_rna.properties['location'].subtype  # Vector
'TRANSLATION'

>>> bpy.types.Object.bl_rna.properties['scale'].subtype  # Vector
'XYZ'
```

The exact rules from code in `bpy_rna.c` are:

* `COLOR`, `COLOR_GAMMA`: use `Color` if length 3; otherwise `bpy_prop_array`.
* `QUATERNION`, `EULER`: use Euler if length 3, or Quaternion if length 4; otherwise `bpy_prop_array`.
* other float vector types: use Vector if length 2, 3, 4; otherwise `bpy_prop_array`.

**Comment by nutti** [comment]
@angavrilov 

> It seems the difference is not reflected in official API documentation, but it is of course known to Blender itself through the subtype property of RNA metadata:

As you may know, fake-bpy-module depends heavily on the official document. (You can see the generation script.)
The generation script parses the docs and output the modules.
https://github.com/nutti/fake-bpy-module/tree/master/src
So, changing the official document itself is easier.

But if you have an idea to get the information from Blender itself including all other information, you can rewrite the analyzer instead of [the original one](https://github.com/nutti/fake-bpy-module/blob/master/src/fake_bpy_module/analyzer.py).
You can fix the generation script of the official document.
https://github.com/blender/blender/blob/master/doc/python_api/sphinx_doc_gen.py

BTW, can these type be changed to `bpy_prop_array`?
I think using `bpy_prop_array` is much easier than parsing RNA metadata.

**Comment by angavrilov** [comment]
I submitted a patch to add this to the documentation: https://developer.blender.org/D16626

**Comment by nutti** [comment]
Thanks.
I think changing the official document seems better to me.
If the patch is merged, I will close this issue.

**Comment by angavrilov** [comment]
Well, it probably will require some changes in the code recognising type descriptions. The patch basically changes the standard "float array of ..." descriptions to "mathutils.Vector of ..." or "mathutils.Quaternion of ..." etc, preserving the ranges, default values and so on.

**Comment by nutti** [comment]
@angavrilov 

You patch is now merged :)
I will revise the parse algorithm later.

**Comment by nutti** [comment]
The parse algorithm is fixed now.
Thanks for your contribution to the official docs @angavrilov .

**Comment by angavrilov** [comment]
What about Matrix? The manual now names it explicitly too.

**Comment by nutti** [comment]
@angavrilov 

Thanks. I forgot about Matrix.
I have committed the patch.
