### ISSUE TITLE
Non-default argument follows default argument

### ISSUE THREAD

**Issue by Koralgoll** [nutti/fake-bpy-module#14]
A SyntaxError occurs when I'm trying to import `bpy` module:
![syntax](https://user-images.githubusercontent.com/9218136/54560257-36008e80-49c2-11e9-9a1d-67694a374d66.jpg)
3rd parameter to `template_list()` function in the `types.py` is default-assigned but several further are not.
![syntax2](https://user-images.githubusercontent.com/9218136/54560267-3c8f0600-49c2-11e9-81a3-cf30d6487a01.jpg)
Is this intended?

**Comment by nutti** [comment]
@Koralgoll 

It seems that this issue is same as #10 
The fake module is generated from `.rst` document.
Below link shows `UILayout.template_list` document.
You can see there is no default argument.

https://docs.blender.org/api/blender2.8/bpy.types.UILayout.html#bpy.types.UILayout.template_list

The fake module can not handle this case.
If I have a time to fix above document, I will try to make patch to Blender itself.

**Comment by nutti** [comment]
I did a temporary fix.

The new pre-made module will be provided after some other bugs are fixed.
