### ISSUE TITLE
Image.pixels is the wrong type

### ISSUE THREAD

**Issue by cmbasnett** [nutti/fake-bpy-module#147]
### System Information

* OS: Windows
* Blender version: 4.0

### Expected behavior

`Image.pixels` should be some sort of generic iterable.

### Description about the bug

`Image.pixels` is a `float` type, indicating it is only a single `float` value, which is incorrect.

### Screenshots/Files [Optional]

![image](https://github.com/nutti/fake-bpy-module/assets/5035660/97827540-75e1-4704-8868-028b5eb5e878)

**Comment by nutti** [comment]
This issue is difficult to solve due to the following reason.

* `Image.pixels` is a dynamic array property which will expose Python API as a 0 element `FloatProperty`. This makes the generated document as a single property. ([Ref](https://github.com/blender/blender/blob/2864c20302513dae0443af461d225b5a1987267a/source/blender/makesrna/intern/rna_image.cc#L1336-L1341))
* The flag of `Image.pixels` contains the `PROP_DYNAMIC` which identifies `FloatProperty` is a dynamic array.
* `PropertyFlag` is not exposed to Python side. This makes us difficult to get flag whether `FloatProperty` is a single or an array.

@cmbasnett 
Do you have an idea to fix this issue?

**Comment by nutti** [comment]
I will close this issue due to the implementation difficulty.

@cmbasnett 
If you have an idea to solve this issue, please send me a comment.

**Comment by Andrej730** [comment]
Posted it to Blender bug tracker - https://projects.blender.org/blender/blender/issues/140904
