### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by esteveUlrico** [nutti/fake-bpy-module#16]
**Description about the feature**  
It would be helpful if I could simply install the fake package via pip/pipenv.

**Are you willing to contribute about this feature. (Yes/No)**  
Sure :-)

**Screenshots** [Optional]  
**Additional comments** [Optional]

**Comment by nutti** [comment]
@esteveUlrico 

Thanks for the great request.  
I'm also thinking about this feature recently.

> Are you willing to contribute about this feature. (Yes/No)
> Sure :-)

If you want to contribute this feature, I'll wait for your pull request.
You can make pull request from the below link.

https://github.com/nutti/fake-bpy-module/pulls

Do you want to try it?

**Comment by nutti** [comment]
@esteveUlrico 

> Are you willing to contribute about this feature. (Yes/No)
> Sure :-)

I would like to ask about this.
Are you willing to contribute this feature?
i.e. Do you want to make codes and Pull Request to support this feature?

If you are not willing to do this, I will develop about this feature.
Thanks.

**Comment by nutti** [comment]
@esteveUlrico 

Please give me your opinion about this feature.
I found that we can only one package to register to PyPI.
This package conflicts to the already registered `bpy` module, and we need to use another package name.
For example, if the name of package is `fake-bpy-module`, you need to import `fake_bpy_module` at first as follows.

```python
from fake_bpy_module import *
import bpy

bpy.app.    # code completion
```

It is useless when we deploy the add-on to blender. (Because we need to delete `from fake_bpy_module import *` every time.)
From this example, I think it is not good method to register PyPI.

What do you think?

**Comment by nutti** [comment]
Ah, I mistook about it.
I can achieve without changing a package name.

Almost all codes are prepared.
I will upload the package after one or two weeks.

**Comment by nutti** [comment]
All versions of fake-bpy-modules are registered to PyPI now.  
So, I will close this issue.

**Comment by StefanUlbrich** [comment]
Hey @nutti  
sorry that I could not contribute in the end: I lost a lot of time during the last two weeks in the hospital due to a health-related issue. Thank you for taking action!

**Comment by nutti** [comment]
@StefanUlbrich 

No problem.
For now, you can install fake-bpy-module from pip-package.
Thanks for the great request!
