### ISSUE TITLE
bpy.props.EnumProperty items parameter incorrectly typed

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#246]
My understanding of [the documentation](https://docs.blender.org/api/current/bpy.props.html#bpy.props.EnumProperty) is that the `items` parameter should have the type

```python
collections.abc.Iterable[tuple[str, str, str] | tuple[str, str, str, int] | tuple[str, str, str, str, int] | None]
| collections.abc.Callable[[typing.Any, bpy.types.Context | None], collections.abc.Iterable[tuple[str, str, str] | tuple[str, str, str, int] | tuple[str, str, str, str, int] | None]]
```

I am happy to create a mod file to enact this change, however I have encountered two issues:
1. If I type the function's input, then `bpy.types` needs to be imported to give access to `Context`
2. Do I really need to copy the entire function definition into the mod file in order to change one parameter's type?

**Comment by nutti** [comment]
This is because `bpy.types.Context` is not processed by DependencyBuilder which resolves the dependency by adding the modules to be imported.
https://github.com/nutti/fake-bpy-module/blob/master/src/fake_bpy_module/transformer/dependency_builder.py

If you want to process `bpy.types.Context` by DependencyBuilder, you need to add `ClassRef` node to it.
So, you may solve this by following code.

```
collections.abc.Iterable[tuple[str, str, str] | tuple[str, str, str, int] | tuple[str, str, str, str, int] | None]
| collections.abc.Callable[[typing.Any, :class:`bpy.types.Context` | None], collections.abc.Iterable[tuple[str, str, str] | tuple[str, str, str, int] | tuple[str, str, str, str, int] | None]]
```
