### ISSUE TITLE
Type Hint Error: "bpy.types.XXXX" to type hint parm type/return type shows "Any"

### ISSUE THREAD

**Issue by atticus-lv** [nutti/fake-bpy-module#259]
### System Information

* OS: Windows
* Blender version: 4.1
* Pycharm

### Description about the bug
seems that type hint is not right
![image](https://github.com/nutti/fake-bpy-module/assets/64118610/dc63b8e2-5621-4f55-979e-526df957f145)

**Comment by Andrej730** [comment]
What module is this?

**Comment by atticus-lv** [comment]
This is not a module but a custom tool class.
The problem is  when  using `bpy.types.XXXX` to type hint a parm type/return type, it always shows `Any`

**Comment by Andrej730** [comment]
Was able to reproduce this.
If you open bpy.types you'll see a warning that PyCharm skips the file because of it's size:
![image](https://github.com/nutti/fake-bpy-module/assets/9417531/1b81d97e-3496-427c-ba8e-6cb8b77ae04c)

You can increase maximum file size in the pycharm settings and restart pycharm, then it will load symbols from bpy.types too and it will work fine.
https://stackoverflow.com/questions/37695939/maximum-file-size-in-pycharm

**Comment by nutti** [comment]
@atticus-lv 

You can also see the same information at the first Note on https://github.com/nutti/fake-bpy-module/blob/master/docs/setup_pycharm.md to solve this issue.

**Comment by atticus-lv** [comment]
thanks, I will check it out. Before I had set `intellisense.filesize` to 2600 just as the readme said. Maybe I should make it larger just like 30000

**Comment by atticus-lv** [comment]
nice, set it to 5000 and it works
![image](https://github.com/nutti/fake-bpy-module/assets/64118610/fa5371f5-522e-4306-b8dc-e4e1ad50fad9)

however the bpy.utils still highlight, old version like 4.0 will not have this issue(set it to 30000 is not work, but when using `from bpy.utils import ...`)
![image](https://github.com/nutti/fake-bpy-module/assets/64118610/3b8c6976-e59a-46df-ad0e-b49e36df9b36)
![image](https://github.com/nutti/fake-bpy-module/assets/64118610/35e49093-5d7e-48c0-ac67-1e9b9d029e1c)

**Comment by nutti** [comment]
I'm not sure whether this issue is unique for PyCharm or not.
From my VSCode environment, I could not find this issue.

**Comment by nutti** [comment]
@atticus-lv Any update?

**Comment by nutti** [comment]
Close this issue due to no response.

**Comment by Wotava** [comment]
@nutti I've come across the same issue in PyCharm as @atticus-lv had with `bpy.utils`, but it seems that the problem runs deeper as code suggestion does not work properly for anything defined outside of `bpy\__init__.pyi`:

![image](https://github.com/user-attachments/assets/70112eff-ce79-4490-8a88-d4317984e94b)

This happens in `fake-bpy-module` versions after `20231118`. In `fake-bpy-module-4.0(20231118)` everything works as expected:

![image](https://github.com/user-attachments/assets/7106c002-8eb8-457a-ac32-05e0173c78c7)

I believe it's due to the change in file structure (files were moved to subfolders like `.\bpy\ops\action.py` -> `.\bpy\ops\action\__init__.pyi`. PyCharm's Intellisense will pick it up if the import is specific, like `from bpy.ops.action import select_all`, but obviously this is not going to work properly in Blender.

**Comment by nutti** [comment]
@atticus-lv 

Your issue seems to relate to #304 .
This kind of issue was discussed on the Discord channel.

Could you try the conversation on the Discord channel?
https://discord.com/channels/1253846991188791418/1253848264483147778/1273613511846793228
