### ISSUE TITLE
Add `addon_utils`

### ISSUE THREAD

**Issue by feliwir** [nutti/fake-bpy-module#26]
**Description about the feature**  
Add the `addon_utils` module aswell. I use this module for my testing setup

**Are you willing to contribute about this feature. (Yes/No)**  
I could contribute, but would probably need some time

**Comment by nutti** [comment]
@feliwir 

Thanks, Nice catch!
fake-bpy-module does not support API which is not listed in API document currently.
But it is a good idea to add APIs such as `addon_utils`.

> I could contribute, but would probably need some time

Great!
But I think it is a bit difficult because all fake-bpy-modules are generated automatically.
If you have any idea to add these APIs to this module, I would like to discuss about it.

Anyway, thank you so much for raising this issue!

**Comment by nutti** [comment]
@feliwir 

Hi, any update about this?
If you don't have much time to tackle this, I will tackle this issue.
Thanks.

**Comment by feliwir** [comment]
Hey @nutti,
Sorry i kind of forgot about this since i gave development of our blender plugin to someone else. So feel free to tackle this issue yourself.

**Comment by nutti** [comment]
Added APIs defined in blender's `modules` directory now.
This feature will be available in next release.
