### ISSUE TITLE
Object.name and bpy.data.materials.new are missing?

### ISSUE THREAD

**Issue by zaha** [nutti/fake-bpy-module#28]
Hi,

first of all great package, really makes working with bpy in VS Code much more convenient. I played around with the pip version for 2.82 today and stumbled over two things that weren't found in the package.

The first is Object.name:
```
bpy.ops.mesh.primitive_cube_add()
current = bpy.context.object
current.name = "Cube" # No code completion or type here
```

And the other one was 
``` 
mat = bpy.data.materials.new(name="Material") # Same here
```

Am I doing something wrong here or are they missing in the package for some reason?

Cheers
Michael

**Comment by nutti** [comment]
@zaha 

Thanks for your report.

> The first is Object.name

We can not complete this because `bpy.context.object` is not deterministic across objects.
https://docs.blender.org/api/current/bpy.types.Object.html#bpy.types.Object

Some objects do not have `name` attribute, and we can not recognize it from static analysis.

> bpy.data.materials.new

fake-bpy-module is generated from [Blender Python API documentation](https://docs.blender.org/api/current/index.html).
We can not complete this API because it is also missing in API documentation.

Recently, we're tring to fix this by generating modules from scripts which run in Blender.

**Comment by nutti** [comment]
@zaha 

I'm so sorry to fix this issue.
This issue is now resolved.
I will new version of fake module in a few day.

The code completion results of newest version are as follows.

<img width="371" alt="github_20200512_2" src="https://user-images.githubusercontent.com/1463952/81657999-5798c100-9473-11ea-8350-f5f7cc0a2f3f.png">

<img width="376" alt="github_20200512_1" src="https://user-images.githubusercontent.com/1463952/81657914-42239700-9473-11ea-9403-40d399594001.png">

I will close this issue.
Please open issue if you have any other issues.

**Comment by zaha** [comment]
Awesome, thanks a lot! :)
