### ISSUE TITLE
Issues with bpy_prop_collection

### ISSUE THREAD

**Issue by skarnproject** [nutti/fake-bpy-module#30]
The main issue I had with fake-bpy-module is that it generates typing.List[SomeType] instead of SomeType for Blender's instances of bpy_prop_collection and its variants. And it also does not generate class inheritance. So, as a result, we have these issues:

bpy.data.objects. -> further type hinting fails, as the generated type is typing.List[BlendDataObjects]

If I change it manually to BlendDataObjects, it works just fine.

Another problem arises due to lack of class inheritance:

mesh = bpy.data.meshes.new(name)( returns  -> ID instead of bpy.types.Mesh)
bpy.data.objects.new(data=mesh) - marked as TypeError in IDE, as returned type of bpy.data.meshes.new() after fixing it itself to BlendDataMeshes is bpy.types.Mesh.

bpy.data.objects.new(data=mesh) would expect an ID class, but got Mesh instead now. TypeError again. I know we can't put bpy.types.Mesh explicitly in there, as object may be created trough a different ID data, e.g. lamp. So, my proposal would be either typing.Union[bpy.types.Mesh, bpy.types.Lamp, etc) or leaving it more implicit as ID, but fixing class inheritance for mesh to derive from ID as stated in Blender API docs. Either way the type becomes valid then.

**Comment by nutti** [comment]
@skarnproject 

Sorry for late response.
Thanks for sharing your issue.

> If I change it manually to BlendDataObjects, it works just fine.

I think type of `bpy.data.objects` should be `typing.Union['BlendDataObjects', typing.List['Object'], 'bpy_prop_collection']` instead of `'BlendDataObjects'` because we could not handle below situation.

```
bpy.data.objects["Cube"].name
```

What do you think?

> bpy.data.objects.new(data=mesh) would expect an ID class, but got Mesh instead now. TypeError again. I know we can't put bpy.types.Mesh explicitly in there, as object may be created trough a different ID data, e.g. lamp. So, my proposal would be either typing.Union[bpy.types.Mesh, bpy.types.Lamp, etc) or leaving it more implicit as ID, but fixing class inheritance for mesh to derive from ID as stated in Blender API docs. Either way the type becomes valid then.

Current version does not consider class inheritance.
But it is good time to add these information to fake-bpy-module.
Thanks for your proposal.

**Comment by nutti** [comment]
@skarnproject 

I fixed this issue.
After few days, I will release new version which includes the patches.

The examples of code completion are as follows.

<img width="472" alt="github_20200512_1" src="https://user-images.githubusercontent.com/1463952/81658938-32f11900-9474-11ea-9761-b6503b949286.png">

<img width="414" alt="github_20200512_2" src="https://user-images.githubusercontent.com/1463952/81658967-397f9080-9474-11ea-8f2d-f48fa9b2c8a1.png">

Thanks for your cooperate.

**Comment by xixixao** [comment]
Hey @nutti these definitions don't work well with Pyright which correctly complains about the collection methods because the type is a union instead of an inheritance:

<img width="739" alt="Screen Shot 2022-11-04 at 18 17 17" src="https://user-images.githubusercontent.com/1473433/200094700-a783d185-8bde-40d1-bdbe-d41eb58d936e.png">


<img width="835" alt="Screen Shot 2022-11-04 at 18 16 23" src="https://user-images.githubusercontent.com/1473433/200094685-8ae7fe88-9855-4d5c-8df3-bdee20f0ed2a.png">
<img width="701" alt="Screen Shot 2022-11-04 at 18 16 49" src="https://user-images.githubusercontent.com/1473433/200094687-2c98f327-c7f4-49a5-8ccb-1aa8c12b7c62.png">


I'm not sure how hard it is do generate but I think the correct type would involve
```python
class BlendDataMeshes(bpy_prop_collection[Mesh])
```

**Comment by nutti** [comment]
@xixixao 

> class BlendDataMeshes(bpy_prop_collection[Mesh])

This is incorrect.
From [the official document](https://docs.blender.org/api/current/bpy.types.BlendDataMeshes.html#bpy.types.BlendDataMeshes), the base class of `BlendDataMeshes` is `bpy_struct` which has new method.
Actually, this works well in VSCode with Pylance environment.

We will not fix this because we want to follow the official document not to increase the maintenance cost.
If you think the official document is wrong, you may send the patch to the Blender itself.
