### ISSUE TITLE
Mocked mathutils conflicts with real mathutils

### ISSUE THREAD

**Issue by ogierm** [nutti/fake-bpy-module#39]
**System Information**
* OS: Windows 10
* Blender version: 2.90

I've tried to install [the real mathutils package](https://pypi.org/project/mathutils/), but `pip` prevented me, saying that the requirement is already satisfied. Since I use the Windows Store version of Python I couldn't actually look up if it was satisfied by one of these fake-bpy-modules, but I could install mathutils on an older Python version, where I don't have any fake-bpy-modules installed.
Either way, I don't see much use in mocking mathutils, if one can install the real thing.

**Comment by nutti** [comment]
@ogierm 

You can't coexist mathutils and fake-bpy-module because pip system does not permit same package.
Perhaps, it may work correctly by installing from [zip file](https://github.com/nutti/fake-bpy-module/releases).
Anyway, this is a specification of pip system, so we could not help with it.

**Comment by ogierm** [comment]
Hmm, I see, maybe there is a way to just mock bpy and not mathutils with the fake-bpy-module? Or have the fake-bpy-module use the real mathutils as a subdependency?

**Comment by nutti** [comment]
@ogierm 

> there is a way to just mock bpy and not mathutils with the fake-bpy-module?

I think you can do this by following below process.

* Install fake-bpy-module from zip file as I shown in previous comment
* Remove `mathutils` directory in fake-bpy-module.

> Or have the fake-bpy-module use the real mathutils as a subdependency?

I think above processes support this.

**Comment by ogierm** [comment]
Adding the zip to the extra paths in VSCode didn't work. I can't remove mathutils from the fake-bpy-module folder, because with the Windows Store pip I apparently can't access that.
Wouldn't it be the best if the fake-bpy-modules scripts excluded the mathutils folder and instead installed the real mathutils? I just don't see the value in general, for any user, to have a mocked version of mathutils, when they could have the real version.

**Comment by nutti** [comment]
@ogierm 

You don't need to install fake-bpy-module to python package directory for the code-completion.
There is another option to achieve this.
You can also do auto-completion with [this process](https://github.com/nutti/fake-bpy-module/blob/master/docs/setup_visual_studio_code.md#setup-ide-visual-studio-code) if you use VSCode.

* Download fake-bpy-module .zip file.
* Remove `mathutils` directory
* Follow [this process](https://github.com/nutti/fake-bpy-module/blob/master/docs/setup_visual_studio_code.md#setup-ide-visual-studio-code)


> Wouldn't it be the best if the fake-bpy-modules scripts excluded the mathutils folder and instead installed the real mathutils? 

I don't think so because mathutils package used in Blender is not exactly same as one in Blender.
Furthermore, Blender may change this package by own way in future.
So we should use the version which is included in Blender.
In addition, we need much more effort to support if we provide the package without mathutils package.

**Comment by ogierm** [comment]
I've been trying to do that for the whole time, but it's just not working. It might just be an issue with the Pylance extension, idk

**Comment by nutti** [comment]
@ogierm 

I think it is not a problem from fake-bpy-module.
In my environment with bare-VSCode, there is no problem to complete with downloaded zip files.

If you interested in generating the module by yourself, you can also make pip package without mathutils.
https://github.com/nutti/fake-bpy-module/blob/master/docs/generate_modules.md
But more steps are needed to exclude mathutils package for now.

**Comment by Andrej730** [comment]
Met this issue one too with the code below. 
It would be nice to either have `mathutils` excluded from `fake-bpy-module` (the actual `mathutils` module should cover it completely) or mention this conflict in [README.md](https://github.com/nutti/fake-bpy-module#readme)

```python
from mathutils import Vector
a = Vector([2.0, 5.0, 3.0])
len(a) # throws TypeError: 'NoneType' object cannot be interpreted as an integer
[i for i in a] # HANGS INDEFINITELY until I do ctrl+c
```
