### ISSUE TITLE
subdir bpy.context does not exist- premade modules 2.79

### ISSUE THREAD

**Issue by YoniChechik** [nutti/fake-bpy-module#6]

**Comment by nutti** [comment]
@asaflotz 

I think `bpy.context` API will be changed by the Blender status.
So, we can not handle this API because this API depends on the status of Blender.

Same conversations are done in Blender Artists.
https://blenderartists.org/t/fake-bpy-modules-for-code-auto-completion-on-ide/697936/7

If you have any idea to solve this, it will be great for me to realize this feature.

**Comment by nutti** [comment]
I found a solution to realize this feature.
Only I need to do is adding the type annotation to bpy.types.Context for bpy.context.
I will add this feature and release soon.

**Comment by nutti** [comment]
Now, this feature is in master branch.
After some code refining and tests, I will upload newest pip package.
