### ISSUE TITLE
Failed to generate modules

### ISSUE THREAD

**Issue by yuriteixeira** [nutti/fake-bpy-module#96]
**System Information**
  
* OS: Mac OS 12.2
* Blender version: 3.0.1

**Expected behavior**  
Script `gen_module.sh` mentioned in https://github.com/nutti/fake-bpy-module/blob/master/docs/generate_modules.md should work. but it doesn't

**Description about the bug**  
The script fails and doesn't generate the module.

**Screenshots/Files** [Optional]  
[gen-module.log](https://github.com/nutti/fake-bpy-module/files/8064448/gen-module.log)

**Comment by nutti** [comment]
@yuriteixeira 

I think this issue seems to be a Blender issue from the log.
Is it possible to follow [Case 2](https://github.com/nutti/fake-bpy-module/blob/master/docs/generate_modules.md#case-2-do-it-yourself-all-procedures) and show me the result?
If the error is issued in [process 4](https://github.com/nutti/fake-bpy-module/blob/master/docs/generate_modules.md#4-generate-rst-documents), the issue seems to be come from Blender itself.

**Comment by nutti** [comment]
@yuriteixeira 

Any update?
I will close this issue in a few days if there is no response.

**Comment by yuriteixeira** [comment]
I've realised the released version is enough for now. Thanks!
